export { default as About } from "./About/About";
export { default as Contact } from "./Contact/Contact";
export { default as Footer } from "./Footer/Footer";
export { default as Hero } from "./Hero/Hero";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Portfolio } from "./Portfolio/Portfolio";
export { default as Service } from "./Service/Service";
export { default as Technology } from "./Technology/Technology";
export { default as Testimonial } from "./Testimonial/Testimonial";
